[package]
name = "sitemap_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.16", features = ["full"] }
tokio = { version = "1.16.1", features = ["full"] }
hyper-tls = "0.5.0"
futures = "0.3.19"
anyhow = "1.0.53"